package src.los.controller;

import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.control.Label;
import src.los.common.PlayerClass;
import src.los.game.SpaceDriver;

import java.io.IOException;

/**
 * The CharacterSelectionController class represents the controller for the character selection screen.
 *
 * This class handles the user's choice of character and initializes the game stage.
 * @author Calvin Vu & Hanxiao Mao
 * @version 1.0
 */
public class CharacterSelectionController {

    public PlayerClass chosenCharacter;

    /**
     * Sets the chosen character to Naruto.
     */
    public void chooseNaruto() { SpaceDriver.chosenCharacter = PlayerClass.NARUTO; }

    /**
     * Sets the chosen character to Sasuke.
     */
    public void chooseSasuke() {
        SpaceDriver.chosenCharacter = PlayerClass.SASUKE;
    }

    /**
     * Handles the user's selection of character.
     * @param event the ActionEvent object generated by the user's selection
     * @throws IOException if there is an I/O error
     */
    public void selectCharacter(ActionEvent event) throws IOException {
        String id = ((Node) event.getSource()).getId();

        if (id.equals("sasuke")) {
            chooseSasuke();
        } else {
            chooseNaruto();
        }
        //Initialize the player class
        initializeGameStage();
    }

    /**
     * Initializes the game stage by creating and showing the game stage scene.
     * @throws IOException if there is an I/O error
     */
    public void initializeGameStage () throws IOException {

        SceneController.getInstance().createGameStage();
        SceneController.getInstance().showGameStage();
    }
}
